[toolchain]
channel = "nightly-2025-02-28"
components = [
    "clippy-preview",
    "rust-analyzer",
    "rust-docs",
    "rust-src",
    "rust-std",
    "rustfmt-preview",
]
targets = [
    "wasm32-unknown-unknown",
]
profile = "default"
