[watch]
watch = ["src/"]
ignore = ["e2e/"]

[[hooks]]
stage = "pre_build"
command = "tailwindcss"
command_arguments = ["-c", "tailwind.config.js", "-i", "style/main.css", "-o", "style/compiled.css", "--minify"]
