name: End-to-End Functional Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    paths:
      - ".github/workflows/e2e-tests.yaml"
      - "src/**"
      - "e2e/**"
      - "index.html"
      - "rust-toolchain.toml"
      - "Cargo.toml"
      - "Cargo.lock"
      - "Trunk.toml"
  push:
    branches:
      - "main"
      - "epic/**"
      - "integration/**"
    paths:
      - ".github/workflows/e2e-tests.yaml"
      - "src/**"
      - "e2e/**"
      - "index.html"
      - "rust-toolchain.toml"
      - "Cargo.toml"
      - "Cargo.lock"
      - "Trunk.toml"

jobs:
  run-tests:
    name: Run End to End Tests
    runs-on: self-hosted
    env:
      RUSTC_WRAPPER: "/home/nicholas/.cargo/bin/sccache"
      CARGO_INCREMENTAL: 0
      END_TO_END_TESTS_HEADLESS: "true"
    steps:
      - name: Skip Duplicate Actions
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
      - if: steps.skip_check.outputs.should_skip != 'true'
        name: Checkout
        uses: actions/checkout@v4.1.1
      - if: steps.skip_check.outputs.should_skip != 'true'
        run: cargo rustc --test e2e -- --emit link="./target/debug/deps/e2e"
      - if: steps.skip_check.outputs.should_skip != 'true'
        run: cargo build --target=wasm32-unknown-unknown
      - if: steps.skip_check.outputs.should_skip != 'true'
        run: geckodriver --port 4444 &
      - if: steps.skip_check.outputs.should_skip != 'true'
        run: trunk serve &
      - if: steps.skip_check.outputs.should_skip != 'true'
        run: sleep 5 && ./target/debug/deps/e2e --fail-fast
