name: End-to-End Functional Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    paths:
      - ".github/workflows/e2e-tests.yaml"
      - "src/**"
      - "e2e/**"
      - "index.html"
      - "rust-toolchain.toml"
      - "Cargo.toml"
      - "Cargo.lock"
  push:
    branches:
      - "main"
      - "epic/**"
      - "integration/**"
    paths:
      - ".github/workflows/e2e-tests.yaml"
      - "src/**"
      - "e2e/**"
      - "index.html"
      - "rust-toolchain.toml"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  run-tests:
    name: Run End to End Tests
    runs-on: self-hosted
    env:
      CARGO_HOME: "/media/nicholas/rust/.cargo"
      RUSTUP_HOME: "/media/nicholas/rust/.rustup"
      RUSTC_WRAPPER: "/media/nicholas/rust/.cargo/bin/sccache"
      CARGO_INCREMENTAL: 0
    steps:
      - name: Skip Duplicate Actions
        uses: fkirc/skip-duplicate-actions@v5.3.1
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - run: cargo rustc --test e2e -- --emit link="./target/debug/deps/e2e"
      - run: cargo build --target=wasm32-unknown-unknown
      - run: geckodriver --port 4444 &
      - run: trunk serve &
      - run: sleep 5 && ./target/debug/deps/e2e --fail-fast
