name: Enforce Formatting

on:
  push:
    branches:
      - "feature/**"
      - "dev/**"
    paths:
      - ".github/workflows/formatting.yaml"
      - "**.md"
      - "**.toml"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    paths:
      - ".github/workflows/formatting.yaml"
      - "**.md"
      - "**.toml"

jobs:
  build:
    name: Checking For Formatting Violations
    runs-on: self-hosted
    env:
      CARGO_HOME: "/media/nicholas/rust/.cargo"
      RUSTUP_HOME: "/media/nicholas/rust/.rustup"
      RUSTC_WRAPPER: "/media/nicholas/rust/.cargo/bin/sccache"
      CARGO_INCREMENTAL: 0
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.12.1
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - run: dprint check --config .dprint.json ./ --allow-no-files
      - run: cargo fmt --all --check
