name: Enforce Formatting

on:
  push:
    branches:
      - "feature/**"
    paths:
      - ".github/workflows/formatting.yaml"
      - "**.md"
      - "**.toml"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    paths:
      - ".github/workflows/formatting.yaml"
      - "**.md"
      - "**.toml"

jobs:
  build:
    name: Checking For Formatting Violations
    runs-on: self-hosted
    steps:
      - name: Skip Duplicate Actions
        uses: fkirc/skip-duplicate-actions@v5.3.1
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - run: dprint check --config .dprint.json ./ --allow-no-files
