name: Markdown Link Checker

on:
  push:
    branches:
      - "feature/**"
    paths:
      - ".github/workflows/markdown-links.yaml"
      - "**.md"
      - "**.html"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    paths:
      - ".github/workflows/markdown-links.yaml"
      - "**.md"
      - "**.html"

jobs:
  build:
    name: Markdown Link Validation
    runs-on: self-hosted
    steps:
      - name: Skip Duplicate Actions
        uses: fkirc/skip-duplicate-actions@v5.3.1
      - run: mlc ./
